export const WalletActionTypes = {
  SET_CURRENT_WALLET: "SET_CURRENT_WALLET",
  ADD_WALLET: "ADD_WALLET",
  GET_WALLETS: "GET_WALLETS",
  SET_INTERVALS: "SET_INTERVALS",
  CHANGE_CURRENT_INTERVAL: "CHANGE_CURRENT_INTERVAL",
  UPDATE_CASH_BALANCE: "UPDATE_CASH_BALANCE",
};
